State how to enable micropipenv in s2i container images
thoth-station/micropipenv pull request #152
Opened 2021-01-05 17:08 UTC by fridex

## This introduces a breaking change

- [x] No

2021-01-05 17:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmicropipenv).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/micropipenv/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-01-06 11:13 UTC, frenzymadness requested changes
I'd just change the wording of the first sentence.

2021-01-06 11:13 UTC, frenzymadness commented on README.rst
> +micropipenv is shipped in UBI, Fedora and RHEL based container images. To
This is not entirely true. If you enable it, it's installed from PyPI during the build of your container. Our plan for the future (next release of RHEL which will have micropipenv as an RPM) is to have it by default installed everywhere and use it as a default for Pipfiles.

2021-01-06 13:05 UTC, fridex commented
Thanks for the review and correction. The sentence has been rephrased.

2021-01-06 13:12 UTC, frenzymadness approved these changes

2021-01-06 13:12 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/micropipenv/pull/152#pullrequestreview-562696833" title="Approved">frenzymadness</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmicropipenv).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/micropipenv/blob/master/OWNERS)~~ [frenzymadness]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-06 13:13 UTC, merged