Add `check` subcommand to validate lockfiles
thoth-station/micropipenv pull request #228
Opened 2022-03-02 16:40 UTC by matt-carr

## Related Issues and Dependencies

n/a

## This introduces a breaking change

- [x] Yes
- [ ] No

`poetry install --deploy` will now raise an exception if the content hash in Poetry.lock is out of sync with pyproject.toml . 

Mitigate by dropping the --deploy flag (all it does is raise a logger warning for this scenario if the python version is mismatched).

## This Pull Request implements

This implements functionality similar to `poetry lock --check` (introduced in 1.2.0a1) - a quick validation that there's no drift between the current requirements file and the existing lockfile. I use a custom python script that leverages some of your private methods in my CI to do the same, and I figured this functionality would be useful for others as well.

## Description

* Added a function to compute the content-hash of the poetry section of pyproject.toml, per [their locker code](https://github.com/python-poetry/poetry/blob/master/src/poetry/packages/locker.py). 
* Added a function to validate that Poetry.lock is up to date with pyproject.toml. 
* Extracted code that does similar for pipenv to its own function. 
* Added the poetry lockfile validation function to `poetry install`. 
* Created a new subcommand `check` to validate that a Pipfile.lock or Poetry.lock are up to date with their respective dependency files. It accepts specification of pipenv or poetry method with the `--method` flag.

2022-03-02 16:40 UTC, sesheta commented
Hi @matt-carr. Thanks for your PR.

I'm waiting for a [thoth-station](https://github.com/orgs/thoth-station/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/thoth-station/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmicropipenv).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-03-02 16:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sesheta** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @sesheta` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmicropipenv).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/micropipenv/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["sesheta"]} -->

2022-03-08 13:16 UTC, goern commented
/ok-to-test

2022-03-08 13:51 UTC, matt-carr commented
Are the cancelled tests actionable by me? What's my next step here? I'm also not sure what those py3.10 failures are about

2022-03-08 15:26 UTC, frenzymadness commented
Could you please add the latest pip release 22.0.4 to this version: https://github.com/thoth-station/micropipenv/blob/d87774d12e3bdc0d16c68bc643a058665dd5ee4a/micropipenv.py#L51 
That should fix the tests and then we should be able to see all results.

2022-03-14 11:39 UTC, frenzymadness commented
The tests are green now. @fridex could you please do a review?

2022-03-14 16:04 UTC, matt-carr commented
Works for me, have it changed in a jiffy

2022-03-15 09:51 UTC, frenzymadness requested changes
It looks very good to me. There is only one thing I don't like - the warning about micropipenv being unable to parse complex Python versions from poetry config is now twice in the code - once in the new `verify_poetry_lockfile` function and it's also still outside the function.
Would it be possible and does it make sense to keep that piece of code only outside the function and let the logging level depend on the deploy attribute?

2022-03-15 19:21 UTC, frenzymadness commented
I don't have a strong opinion on that. @fridex what do you think? Is the debug warning message useful or do we want to warn users about the potential Python version mismatch only when deploy is specified?

2022-03-16 09:20 UTC, fridex commented
I don't have a strict opinion on this one either. Maybe to be more defensive here, I am more inclined to keep the warning message as some issues might arise even during the installation process so users could be warned.

Not to be too nitpicking with the contribution, I'm fine with merging this and I'm open to submitting a PR to discuss this eventually further - I can imagine a simple function `_get_poetry_python_version` that could be used on both places to propagate the warning.

2022-03-16 13:33 UTC, matt-carr commented
> Maybe to be more defensive here, I am more inclined to keep the warning message as some issues might arise even during the installation process so users could be warned.

This makes sense to me - I'll extract the version checking to a function (TBH I'm not sure why I didn't just do this in the first place)

2022-03-18 08:13 UTC, frenzymadness reviewed
Only one small comment from me and we are good to merge this. Thanks a lot for your effort!

2022-03-18 08:13 UTC, frenzymadness commented on micropipenv.py
> +        if python_version != _get_installed_python_version():
Nitpick: we can save the result of `_get_installed_python_version()` and use it in the error message below instead of `sys.version_info`.

2022-03-18 13:59 UTC, frenzymadness approved these changes

2022-03-18 13:59 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/micropipenv/pull/228#pullrequestreview-914397760" title="Approved">frenzymadness</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmicropipenv).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/micropipenv/blob/master/OWNERS)~~ [frenzymadness]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-18 14:01 UTC, merged

2022-03-18 14:04 UTC, frenzymadness commented
Well, the bot merged the PR before CI finishes its job. Is that correct, @fridex ?

2022-03-21 16:52 UTC, fridex commented
> Well, the bot merged the PR before CI finishes its job. Is that correct, @fridex ?

This might be a configuration of required checks maybe. CC @harshad16 who will know better.

2022-03-21 17:48 UTC, harshad16 commented
ack, yes it is due to configuration 
i will update the CI requirement, to merge only after all ci checks have run.
as here we have separate ci for checks and merge, that was the issue.